### ISSUE TITLE
Lenovo V580c

### ISSUE THREAD

**Issue by Nonstopus** [leecher1337/thinkpad-Lx30-ec#1]
Good afternoon, is it possible to adapt the patch to Lenovo V580s? This model is on the same hardware platform as the B590 laptop.

**Comment by leecher1337** [comment]
Yes, should be possible. It's just on a different offset.
B590 Battery offset patches for H9EC09WW(1.02) start at 28986, those for H1EC33WW(1.13) and H5EC33WW(1.13) start at 28ab8. 
For h1et73ww, the firmware starts at 0x800000 in FW file, for other, it's 0x400000

Will try to update patcher if I have some time, I may also adapt the thinkpad-ec pullrequest for permanent patching.

**Comment by Nonstopus** [comment]
Hello, I have tested the update. I booted from the ISO and when I choose to patch the V580c H1... I get the error:
https://ibb.co/bgSw2Lk
After that, I added the patches to the script ../../../B590/patches/bat/patch.sh. I replaced /bin/bash with /bin/sh. After that, the script started working, but reported that the pattern was not found.
https://ibb.co/bgSw2Lk
My current firmware is:
https://ibb.co/tBHLfhQ
Thank you for your work.

**Comment by leecher1337** [comment]
Hm, can you dump ec memory and upload it here? That would make checking the script easier for me without owning such a machine. I only made a "dry mode" test by patching the firmware update file and that worked.

You should be able to dump the ec memory to a file when booting the ISO and possibly scp it to your host and then upload it here.
```
dd if=/sys/kernel/debug/ec/ec0/ram bs=1 count=$((0x18000)) of=ec.bin
```

Hopefully that works.

**Comment by leecher1337** [comment]
If you feel lucky, you can also try the permanent patches that I added to
https://github.com/leecher1337/thinkpad-ec/tree/Lx30

No guarantee that it works, as I don't have the Notebook model here to physically test it.
It's your choice if you first want to try it in-memory (that isn't really risky, worst thing that can happen is that the EC crashes and you need to powercycle by removint AC and battery), that would require you to dump memory as mentioned above for comparison.
Or if you want to try to permanently patch it (then only an SPI flash chip clip may help you to get out of trouble in the event that something goes wrong).
I can just say that my patches worked without issues on L430.

**Comment by Nonstopus** [comment]
My dump of EC memory is here https://easyupload.io/g35zqe

**Comment by leecher1337** [comment]
Hm, looks like this is only the RAM Part...
Can you try to dum RAM and app memory?
```
dd if=/sys/kernel/debug/ec/ec0/ram  bs=1 count=$((0x40000))  of=ec.bin
```
thx.

**Comment by Nonstopus** [comment]
https://easyupload.io/1663qa

**Comment by leecher1337** [comment]
Hm, interesting, the patterns match just fine.
You mentioned that you got an error and so you replaced /bin/bash with /bin/sh (which could be a problem if bash is not the default shell). However, you pasted the same image twice.
Was this on purpose or was there another error message (that made you replace /bin/bash) and you just accidentally pasted the same error message image twice?

**Comment by Nonstopus** [comment]
Sorry, I made a mistake when I attached the screenshots.
Before I made the changes, the error was:
https://ibb.co/4tL8JNL
After the changes, the error is this:
https://imgbb.com/bgSw2Lk

**Comment by leecher1337** [comment]
New ISO released, that should fix the bash-error, maybe it also fixed the other problem?

**Comment by Nonstopus** [comment]
Yes, everything is working now. I'm happy :)
I am very grateful for you, thank you!

**Comment by leecher1337** [comment]
Good to hear! Don't forget that the patch only lasts until you pull both AC and battery, so if you want to make it permanent, use abovementioned thinkpad-ec (at your own risk).
