### ISSUE TITLE
ThinkPad T470

### ISSUE THREAD

**Issue by soullesseol** [leecher1337/thinkpad-Lx30-ec#3]
Sorry, I have little to none knowledge about it, do you think possible that the in memory patch works for the ThinkPad T470? 
I´m after the battery not recognized bypass, because I can´t find a reliable place to by geniune battery in my country, and nor Amazon has geniune batteries listed (bought one and is not working).

**Comment by leecher1337** [comment]
This repository is about the NUVOTON Controller.
The Thinkpad T470, according to [Schematics](https://drive.google.com/file/d/1KS10A_OyCa1Ok2vtATJVqdvx4D0vNLis/view) has a MEC1653 embedded controller and therefore this repository is also not suitable for this model.
So you won't have any luck with the memory patch either.
Analyzing the EC of the T470 would be a completely new project and obviously is a lot of work.

**Comment by soullesseol** [comment]
you are very kind and I appreciate your response a lot.
